component: http
name: eggDemo
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs12.16
    framework: egg
    name: ${name}
  apigw:
    protocols:
      - http
      - https
app: unmanned-ordering-app-1ab4b30c
